
get_G([Len1, Len2, Len3], [l1, l2, l3], [m1,m2,m3],Q(1,:))

%%

% get coriolis force matrix from limb segment lengths, CoMs, masses, joint 
% angles and joint velocites
function C = get_C(Ls, COMs, Ms, Angs, Vels)
    C = zeros(3);

    C(3,3) =  0;
    C(2,3) = Ms(3)*(COMs(3)-Ls(3))*Ls(2)*cos(Angs(3))*(Vels(1)+Vels(2)+Vels(3));
    C(1,3) = C(2,3) + Ms(3)*(COMs(3)-Ls(3))*Ls(1)*Vels(3)*cos(Angs(2) + Angs(3)) + ...
        Ms(3)*(COMs(3)- Ls(3))*Ls(1)*cos(Angs(3))*(Vels(1) + Vels(2));

    C(3,2) = Ms(3)*Ls(2)*(Ls(3)-COMs(3))*cos(Angs(3))*(Vels(1)+Vels(2));
    C(2,2) = Ms(3)*(COMs(3)-Ls(3))*Ls(2)*cos(Angs(3))*(Vels(3));
    C(1,2) = Ms(3)*(COMs(3)-Ls(3))*Ls(2)*cos(Angs(3))*(Vels(3)) + ...
        Ms(3)*(COMs(3)-Ls(3))*Ls(1)*Vels(3)*cos(Angs(2) + Angs(3)) + ...
        Ms(3)*(COMs(3)- Ls(3))*Ls(1)*cos(Angs(3))*(Vels(1) + Vels(2)) - ...
         Ms(3)*(Ls(2))*Ls(1)*sin(Angs(2))*(Vels(1)+Vels(2)) + ...
         Ms(2)*(COMs(2)-Ls(2))*Ls(1)*sin(Angs(2))*(Vels(1)+Vels(2));

    C(3,1) = Ms(3)*Ls(2)*(Ls(3)-COMs(3))*cos(Angs(3))*(Vels(1)+Vels(2)) + ...
        Ms(3)*Ls(1)*(Ls(3)-COMs(3))*cos(Angs(2)+Angs(3))*Vels(1);
    C(2,1) = Ms(3)*(COMs(3)-Ls(3))*Ls(2)*cos(Angs(3))*(Vels(3)) + ...
        Ms(3)*Ls(1)*Ls(2)*sin(Angs(2))*Vels(1) + ...
        Ms(3)*Ls(1)*(Ls(3)-COMs(3))*cos(Angs(2)+Angs(3))*Vels(1) - ...
        Ms(2)*(COMs(2)-Ls(2))*Ls(1)*sin(Angs(2))*(Vels(1));
    C(1,1) = -Ms(2)*(COMs(2)-Ls(2))*Ls(1)*sin(Angs(2))*(Vels(1)) + ...
        Ms(2)*(COMs(2)-Ls(2))*Ls(1)*sin(Angs(2))*(Vels(1)+Vels(2)) + ...
        Ms(3)*Ls(1)*Ls(2)*sin(Angs(2))*Vels(1) - ... 
        Ms(3)*(Ls(2))*Ls(1)*sin(Angs(2))*(Vels(1)+Vels(2)) + ...
        Ms(3)*(COMs(3)-Ls(3))*Ls(2)*cos(Angs(3))*(Vels(3)) + ...
        Ms(3)*(COMs(3)- Ls(3))*Ls(1)*cos(Angs(3))*(Vels(1) + Vels(2)) + ...
        Ms(3)*(COMs(3)-Ls(3))*Ls(1)*Vels(3)*cos(Angs(2) + Angs(3)) + ...
        Ms(3)*Ls(1)*(Ls(3)-COMs(3))*cos(Angs(2)+Angs(3))*Vels(1);
end

% Get mass matrix for lower limb given segment lengths, COMs, masses,
% and joint angles
function M = get_M(Ls, COMs, Ms, Angs)
    M = zeros(3);

    M(3,3) = Ms(3)*(COMs(3)^2 + Ls(3)^2 - 2*COMs(3)*Ls(3));

    M(2,3) = M(3,3) + Ms(3)*(COMs(3)*Ls(2)*sin(Angs(3)) - Ls(3)*Ls(2)*sin(Angs(3)));
    M(3,2) = M(2,3);

    M(1,3) = M(3,3) + Ms(3)*(sin(Angs(3))*(COMs(3)*Ls(2) - Ls(3)*Ls(2)) + ...
        sin(Angs(2)+Angs(3))*(COMs(3)*Ls(1) - Ls(3)*Ls(1)));
    M(3,1) = M(1,3);

    M(2,2) = M(3,3) + Ms(3)*(Ls(2)^2 + 2*COMs(3)*Ls(2)*sin(Angs(3)) - ...
        2*Ls(3)*Ls(2)*sin(Angs(3))) + Ms(2)*(COMs(2)^2 + Ls(2)^2 - 2*COMs(2)*Ls(2));

    M(1,2) = M(3,3) + Ms(3)*(Ls(2)^2 + Ls(1)*Ls(2)*cos(Angs(2)) + ...
        COMs(3)*Ls(1)*(sin(Angs(2)) + sin(Angs(3))) - ...
        Ls(3)*Ls(1)*(sin(Angs(2)) + sin(Angs(3))) - 2*Ls(3)*Ls(2)*sin(Angs(3)) + ...
        2*Ls(2)*COMs(3)*sin(Angs(3))) + ...
        Ms(2)*(Ls(2)^2 + COMs(2)^2 -2*Ls(2)*COMs(2) - COMs(2)*Ls(1)*cos(Angs(2))+...
        Ls(2)*Ls(1)*cos(Angs(2)));
    M(2,1) = M(1,2);

    M(1,1) = M(3,3) + Ms(3)*(Ls(1)^2 + 2*Ls(1)*Ls(2)*cos(Angs(2)) + Ls(2)^2 + ...
        2*Ls(1)*COMs(3)*(sin(Angs(2)) + sin(Angs(3)))  - ...
        2*Ls(1)*Ls(3)*(sin(Angs(2)) + sin(Angs(3))) - 2*Ls(2)*Ls(3)*sin(Angs(3)) + ...
        2*COMs(3)*Ls(2)*sin(Angs(3))) + ...
        Ms(2)*(Ls(2)^2 + COMs(2)^2 -2*Ls(2)*COMs(2) - 2*COMs(2)*Ls(1)*cos(Angs(2)) + ...
        2*Ls(2)*Ls(1)*cos(Angs(2)) + Ls(1)^2) + ...
        Ms(1)*(Ls(1)^2 + COMs(1)^2 -2*Ls(1)*COMs(1));
end


% Get gravity vector for lower limb given segment lengths, COMs, masses 
% and angles. Assume gravity as -9.81m/s
function G = get_G(Ls, COMs, Ms, Angs)
    G = zeros(3,1);
    g = 9.81;
    G(1) = Ms(3)*(Ls(3) - COMs(3))*cos(Angs(1)+Angs(2)+Angs(3)) + ...
        Ms(3)*Ls(2)*sin(Angs(1)+Angs(2)) + ...
        Ms(3)*Ls(1)*sin(Angs(1)) + ...
        Ms(2)*(Ls(2)-COMs(2))*sin(Angs(1)+Angs(2)) + ...
        Ms(2)*Ls(1)*sin(Angs(1)) + ...
        Ms(1)*(Ls(1)-COMs(1))*sin(Angs(1));
    G(2) = Ms(3)*(Ls(3) - COMs(3))*cos(Angs(1)+Angs(2)+Angs(3)) + ...
        Ms(3)*Ls(2)*sin(Angs(1)+Angs(2)) + ...
        Ms(2)*(Ls(2)-COMs(2))*sin(Angs(1)+Angs(2));
    G(3) = Ms(3)*(Ls(3) - COMs(3))*cos(Angs(1)+Angs(2)+Angs(3));
    G = G*g;
end
